export const skillsData=[
    {
        
        data:[
            {
                skillName:"HTML",
                percentage:"90"
            },
            {
                skillName:"CSS",
                percentage:"60"
            },
            {
                skillName:"JAVASCRIPT",
                percentage:"75"
            },
            {
                skillName:"PHP",
                percentage:"80"
            },
            {
                skillName:"PYTHON",
                percentage:"60"
            },
            {
                skillName:"MYSQL",
                percentage:"80"
            },
            {
                skillName:"MONGODB",
                percentage:"80"
            },
            {
                skillName:"UML",
                percentage:"80"
            },
            {
                skillName:"AGILE",
                percentage:"90"
            },
            {
                skillName:"BOOSTRAPOS",
                percentage:"50"
            },
            {
                skillName:"REACT.JS",
                percentage:"70"
            },
            {
                skillName:"LARAVEL",
                percentage:"90"
            },
        ]
    },
    {
       
        data:[
            {
                skillName:"JIRA",
                percentage:"90"
            },
            {
                skillName:"GIT",
                percentage:"90"
            },
            {
                skillName:"GITHUB",
                percentage:"80"
            },
            {
                skillName:"NODE.JS",
                percentage:"60"
            },
            {
                skillName:"JQUERY",
                percentage:"60"
            },
            {
                skillName:"GESTION DES DONNEES",
                percentage:"70"
            },
            {
                skillName:"POWERPOINT",
                percentage:"50"
            },
            {
                skillName:"EXCEL",
                percentage:"50"
            },
            {
                skillName:"WORD",
                percentage:"50"
            },
            {
                skillName:"POO",
                percentage:"70"
            },
            {
                skillName:"CLOUD COMPUTING",
                percentage:"50"
            },
            {
                skillName:"JWT",
                percentage:"50"
            },
        ]
    }
]